import { notFound } from "next/navigation"
import RecipeDetailPage from "@/components/recipe-detail-page"

const recipes = {
  "butter-chicken": {
    id: "butter-chicken",
    name: "Butter Chicken",
    image: "/images/butter-chicken.jpg",
    time: "45 mins",
    serves: "4 people",
    difficulty: "Medium",
    ingredients: [
      "500g boneless chicken, cut into pieces",
      "1 cup heavy cream",
      "2 tbsp Parivar Butter Chicken Masala",
      "1 tsp Parivar Haldi (Turmeric)",
      "1 tsp Parivar Mirchi (Red Chili) Powder",
      "2 tbsp tomato puree",
      "1 tbsp ginger-garlic paste",
      "2 tbsp butter",
      "1 medium onion, finely chopped",
      "Salt to taste",
      "Fresh coriander for garnish",
    ],
    instructions: [
      "Marinate chicken pieces with Parivar Haldi, Parivar Mirchi powder, and salt for 30 minutes.",
      "Heat butter in a pan and cook marinated chicken until golden brown. Set aside.",
      "In the same pan, sauté onions until golden, then add ginger-garlic paste.",
      "Add tomato puree and cook for 5 minutes until oil separates.",
      "Add Parivar Butter Chicken Masala and cook for 2 minutes until fragrant.",
      "Return chicken to the pan and mix well with the masala.",
      "Pour in heavy cream and simmer for 10-15 minutes until chicken is cooked through.",
      "Garnish with fresh coriander and serve hot with rice or naan.",
    ],
    parivarrSpices: ["Butter Chicken Masala", "Haldi (Turmeric)", "Mirchi Powder"],
    tips: [
      "Use Parivar Garam Masala for extra flavor depth",
      "Let the chicken marinate longer for better taste",
      "Adjust cream quantity based on desired richness",
    ],
  },
  "chicken-biryani": {
    id: "chicken-biryani",
    name: "Chicken Biryani",
    image: "/images/chicken-biryani.jpg",
    time: "90 mins",
    serves: "6 people",
    difficulty: "Hard",
    ingredients: [
      "500g basmati rice",
      "750g chicken, cut into pieces",
      "2 tbsp Parivar Biryani Masala",
      "1 tsp Parivar Haldi (Turmeric)",
      "2 tsp Parivar Mirchi Powder",
      "1 cup yogurt",
      "2 large onions, sliced and fried",
      "1/4 cup ghee",
      "Whole spices (bay leaves, cardamom, cinnamon)",
      "Saffron soaked in warm milk",
      "Fresh mint and coriander leaves",
      "Salt to taste",
    ],
    instructions: [
      "Marinate chicken with yogurt, Parivar Biryani Masala, Parivar Haldi, Parivar Mirchi powder, and salt for 1 hour.",
      "Soak basmati rice for 30 minutes, then boil with whole spices until 70% cooked.",
      "In a heavy-bottomed pot, heat ghee and cook marinated chicken until tender.",
      "Layer the partially cooked rice over the chicken.",
      "Sprinkle fried onions, mint, coriander, and saffron milk on top.",
      "Cover with aluminum foil, then place the lid tightly.",
      "Cook on high heat for 3-4 minutes, then reduce to low heat for 45 minutes.",
      "Let it rest for 10 minutes before opening. Gently mix and serve hot.",
    ],
    parivarrSpices: ["Biryani Masala", "Haldi (Turmeric)", "Mirchi Powder"],
    tips: [
      "Use aged basmati rice for best results",
      "Don't skip the resting time after cooking",
      "Parivar Garam Masala can be added for extra aroma",
    ],
  },
  "dal-tadka": {
    id: "dal-tadka",
    name: "Dal Tadka",
    image: "/images/dal-tadka.jpg",
    time: "30 mins",
    serves: "4 people",
    difficulty: "Easy",
    ingredients: [
      "1 cup yellow lentils (toor dal)",
      "1 tsp Parivar Haldi (Turmeric)",
      "1 tsp Parivar Jeera (Cumin) Seeds",
      "1/2 tsp Parivar Mirchi Powder",
      "2 tbsp ghee",
      "1 tsp mustard seeds",
      "2 dried red chilies",
      "1 medium onion, chopped",
      "2 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "Fresh coriander leaves",
      "Salt to taste",
    ],
    instructions: [
      "Wash and cook lentils with Parivar Haldi and salt in a pressure cooker for 3-4 whistles.",
      "Mash the cooked dal and keep aside.",
      "Heat ghee in a pan, add Parivar Jeera seeds and mustard seeds.",
      "When seeds splutter, add dried red chilies and chopped onions.",
      "Sauté until onions turn golden brown.",
      "Add ginger-garlic paste and cook for 1 minute.",
      "Add tomatoes and Parivar Mirchi powder, cook until tomatoes are soft.",
      "Pour this tempering over the cooked dal and simmer for 5 minutes.",
      "Garnish with fresh coriander and serve hot with rice.",
    ],
    parivarrSpices: ["Haldi (Turmeric)", "Jeera (Cumin)", "Mirchi Powder"],
    tips: [
      "Add Parivar Garam Masala at the end for enhanced flavor",
      "Consistency should be neither too thick nor too thin",
      "Fresh curry leaves in tempering add great aroma",
    ],
  },
  "rajma-curry": {
    id: "rajma-curry",
    name: "Rajma Curry",
    image: "/images/rajma-curry.jpg",
    time: "60 mins",
    serves: "4 people",
    difficulty: "Medium",
    ingredients: [
      "2 cups kidney beans (rajma), soaked overnight",
      "2 tbsp Parivar Rajma Masala",
      "1 tsp Parivar Haldi (Turmeric)",
      "1 tsp Parivar Mirchi Powder",
      "2 large onions, finely chopped",
      "3 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "2 tbsp oil",
      "1 bay leaf",
      "1 tsp Parivar Jeera (Cumin) Seeds",
      "Fresh coriander leaves",
      "Salt to taste",
    ],
    instructions: [
      "Pressure cook soaked rajma with salt and Parivar Haldi for 5-6 whistles until soft.",
      "Heat oil in a pan, add bay leaf and Parivar Jeera seeds.",
      "Add chopped onions and sauté until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add tomato puree and cook until oil separates.",
      "Add Parivar Rajma Masala and Parivar Mirchi powder, cook for 2 minutes.",
      "Add cooked rajma with its water and mix well.",
      "Simmer for 15-20 minutes until curry thickens.",
      "Garnish with fresh coriander and serve with rice.",
    ],
    parivarrSpices: ["Rajma Masala", "Haldi (Turmeric)", "Mirchi Powder", "Jeera (Cumin)"],
    tips: [
      "Soak rajma overnight for better cooking",
      "Mash some beans to thicken the curry naturally",
      "Add Parivar Garam Masala for extra warmth",
    ],
  },
  "chole-bhature": {
    id: "chole-bhature",
    name: "Chole Bhature",
    image: "/images/chole-bhature.jpg",
    time: "75 mins",
    serves: "4 people",
    difficulty: "Medium",
    ingredients: [
      "2 cups chickpeas (chole), soaked overnight",
      "2 tbsp Parivar Chole Masala",
      "1 tsp Parivar Haldi (Turmeric)",
      "1 tsp Parivar Mirchi Powder",
      "2 large onions, chopped",
      "3 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "2 tbsp oil",
      "1 tsp Parivar Jeera (Cumin) Seeds",
      "2 green chilies, slit",
      "Fresh coriander and mint leaves",
      "Salt to taste",
    ],
    instructions: [
      "Pressure cook soaked chickpeas with salt and Parivar Haldi for 6-7 whistles.",
      "Heat oil in a pan, add Parivar Jeera seeds and green chilies.",
      "Add chopped onions and cook until golden brown.",
      "Add ginger-garlic paste and sauté for 2 minutes.",
      "Add tomatoes and cook until they break down completely.",
      "Add Parivar Chole Masala and Parivar Mirchi powder, cook for 3 minutes.",
      "Add cooked chickpeas with their water and mix well.",
      "Simmer for 20-25 minutes, mashing some chickpeas to thicken.",
      "Garnish with fresh coriander and mint, serve hot with bhature.",
    ],
    parivarrSpices: ["Chole Masala", "Haldi (Turmeric)", "Mirchi Powder", "Jeera (Cumin)"],
    tips: [
      "Add tea bags while cooking chickpeas for darker color",
      "Use Parivar Garam Masala for authentic taste",
      "Let the curry rest for better flavor development",
    ],
  },
  "paneer-makhani": {
    id: "paneer-makhani",
    name: "Paneer Makhani",
    image: "/images/paneer-makhani.jpg",
    time: "35 mins",
    serves: "4 people",
    difficulty: "Easy",
    ingredients: [
      "400g paneer, cubed",
      "1 cup heavy cream",
      "2 tbsp Parivar Paneer Masala",
      "1 tsp Parivar Haldi (Turmeric)",
      "1/2 tsp Parivar Mirchi Powder",
      "2 tbsp tomato puree",
      "1 tbsp ginger-garlic paste",
      "2 tbsp butter",
      "1 medium onion, chopped",
      "1 tsp Parivar Kasturi Methi",
      "Salt to taste",
    ],
    instructions: [
      "Heat butter in a pan and lightly fry paneer cubes until golden. Set aside.",
      "In the same pan, sauté onions until translucent.",
      "Add ginger-garlic paste and cook for 1 minute.",
      "Add tomato puree and cook until oil separates.",
      "Add Parivar Paneer Masala, Parivar Haldi, and Parivar Mirchi powder.",
      "Cook the masala for 2-3 minutes until fragrant.",
      "Add cream and simmer for 5 minutes.",
      "Gently add fried paneer and Parivar Kasturi Methi.",
      "Simmer for 5-7 minutes and serve hot with naan or rice.",
    ],
    parivarrSpices: ["Paneer Masala", "Haldi (Turmeric)", "Mirchi Powder", "Kasturi Methi"],
    tips: [
      "Don't overcook paneer to keep it soft",
      "Parivar Kasturi Methi adds authentic restaurant flavor",
      "Adjust cream for desired richness",
    ],
  },
}

export default function RecipePage({ params }: { params: { slug: string } }) {
  const recipe = recipes[params.slug as keyof typeof recipes]

  if (!recipe) {
    notFound()
  }

  return <RecipeDetailPage recipe={recipe} />
}

export function generateStaticParams() {
  return Object.keys(recipes).map((slug) => ({
    slug,
  }))
}
